AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    slinker-serverless

    SAM Template for slinker


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:
  CreateSlinkFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: slinker_serverless/
      Handler: handler.create
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        CreateSlink:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slink
            Method: post

  GetSlinkFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: slinker_serverless/
      Handler: handler.get
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CreateSlink:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slink/{uid}
            Method: get


  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: "Slink"
      AttributeDefinitions:
        - AttributeName: uid
          AttributeType: S
      KeySchema:
        - AttributeName: uid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


Outputs:
  CreateSlinkApi:
    Description: "API Gateway endpoint URL for Slink functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/slink/"

  GetSlinkFunction:
    Description: "GetSlink Lambda Function ARN"
    Value: !GetAtt GetSlinkFunction.Arn

  CreateSlinkFunction:
    Description: "CreateSlink Lambda Function ARN"
    Value: !GetAtt CreateSlinkFunction.Arn

  DynamoDBTableArn:
    Description: "The ARN of your DynamoDB Table"
    Value: !GetAtt DynamoDBTable.Arn
